---
- hosts: public:agent:add-agent
  remote_user: "{{ansible_user}}"
  tasks:
    - name: metricbeat install
      command: "{{ item }}"
      with_items:
        - curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.2.1-x86_64.rpm
        - sudo rpm -vi metricbeat-6.2.1-x86_64.rpm
        - sudo mv /etc/metricbeat/metricbeat.yml /etc/metricbeat/metricbeat.yml.bk
      ignore_errors: True
    - name: metricbeat file copy
      become: true
      become_method: sudo
      copy:
        src: ./metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
        owner: root
        group: root
        mode: 0644
    - name: metricbeat start
      command: "{{ item }}"
      with_items:
        - sudo systemctl enable metricbeat
        - sudo service metricbeat start

    - name: filebeat install
      command: "{{ item }}"
      with_items:
        - curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.2-x86_64.rpm
        - sudo rpm -vi filebeat-6.2.2-x86_64.rpm
        - sudo mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.bk
      ignore_errors: True
    - name: filebeat file copy
      become: true
      become_method: sudo
      copy:
        src: ./filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: 0644
    - name: filebeat start
      command: "{{ item }}"
      with_items:
        - sudo systemctl enable filebeat
        - sudo service filebeat start